### ISSUE TITLE
Milestone: Scala 3 (Dotty) Support

### ISSUE THREAD

**Issue by xerial** [wvlet/airframe#1077]
# Scala 3 (dotty)
- [x] Use Scala 3.0.0 #1639 
- [x] Add a basic configuration
- [x] Extract AirSpec as an external project #1992 
- [x] Test Scala version sandwitch https://github.com/sbt/sbt/pull/5767
- [x] airframe-log support #867 #1381 
- [x] Surface support  #1384
   - [x] Surface.of[X] #1385 
   - [x] Surface.methodsOf[X] #1403 
- [x] airframe-di support #1649 
   - [x] Split source folder for Scala 2 and 3 #1405 
   - [x] Support Scala3 macros #1407 
   - [x] deprecate in-trait bindings #1653 
   - ~[ ] new A with DISupport https://github.com/wvlet/airframe/issues/1410~
   - ~[ ] Traverse Template node in Scala 3 for rewriting `new A with DISupport {}` code~ https://github.com/lampepfl/dotty/issues/10931
- [x] AirSpec #1659
- [x] Use TastyInspector
   - [x] Create ReflectSurface factory
   - [x] RuntimeSurface.of[X]
- [x] Run all AirSpec tests 
     - [x] parquet #2209 Need to resolve Surface of nested objects at runtime or pre-register Surfaces
     - [x] grpc (Need to register trait factories to start gRPC server. https://github.com/wvlet/airframe/issues/2194
       - [x] Scala 3.1.3-RC2 or later will be required for generating new class from a trait type T https://github.com/lampepfl/dotty/issues/11685) 
     - [x] airframe-log
     - [x] surface
        - [x] recursive surface (with type substitution)
        - [x] local surface inside object or class #1695 
        - [x] NamedParameterTest
        - [x] RecursiveHigherKindTypeTest #2052 
     - [x] di
     - [x] codec
     - [x] json
     - [x] msgpack
     - [x] canvas
     - [x] control
     - [x] ulid
     - [x] metrics
     - [x] rx
     - [x] okhttp (~Finagle server is used for testing~) #2440 #2865
     - [x] http-recorder (Finagle server is used internally) #1146 
- [x] airframe-config
- [x] airframe-http
- [x] airframe-http-router
- [x] airframe-http-grpc (codec is required)
  - [x] airframe-http-router
  - [x] airframe-http-codegen (Need to read Surfaces of RPC/Endpoint interfaces from classpath)
     - [x] Fix (or remove the usage of) unstable Tasty-based surface #1698 See also #2006 for more context
- ~[ ] airframe-http-finagle (Finagle must be migrated to Scala 3)~ Finagle will not migrate to Scala 3 soon
- [x] canvas
- [x] codec
   - [x]  Split code for Scala 2 and 3 #1640 
- [x] control
- [x] jmx
- [x] launcher
- [x] metrics
- [x] msgpack
- [x] json
- [x] rx
- [x] rx-html
- [x] rx-html-widget
- [x] parquet
- [x] ulid
- [x] Cross build for Scala.js + Scala 3.0.0
   - [x] Extract sbt-airframe as a separate project #1686 
   - [x] Surface (Use Scala 3 inline methods for JS src) #1676
   - [x] AirSpec for Scala.js + Scala 3.0.0 #2202

**Comment by deabreu** [comment]
Hi, I'm researching alternative frameworks for web development in Scala, as I want to move away from Akka, which would include Play and Lagom.

A few weeks ago, I've come to know Airframe and the possibility to move to Scala 3 caught my attention.

I see this is not completed but much of the work is done already. So I want to ask if you think it should be ok to start a new project in Airframe using Scala 3 only.

**Comment by xerial** [comment]
@deabreu I understand the issues around Finagle (no Scala 3 support) or Akka (adopted business license).

For Scala 3, Netty or gRPC backend of airframe-http will be promising (and the basic functionalities are already working),  but it's not production ready at this moment. I'm trying to implement the remaining pieces such as https://github.com/wvlet/airframe/pull/2689, for supporting all of the functionalities in Scala 3

**Comment by xerial** [comment]
@takezoe @shimamoto @exoego @yuokada All of the Scala 3 migration work has been completed! Thank you for all of your contributions so far. 

Although the documentation needs some updates around the new RxRouter and RxFilter usage, I'm still expecting to have some interface changes while building real applications using Scala 3. I'll update the doc once these new interfaces for Scaal 3 become stable. Especially, Netty-based HTTP server backend and Rx-based filters have not been battle-tested yet. 

Around Scala.js, fastOptJs, npm-bundler, building facade manually become obsolete, and we now can use YARN, fastLinkJS, Vite.js, scalablyTyped, etc., which enable seamless integration with the JS ecosystem. https://www.scala-js.org/doc/tutorial/scalajs-vite.html I'll dig into how to set up projects using these new standards.

**Comment by xerial** [comment]
@deabreu Airframe 23.5.0 has been released. Scala 3 is now fully supported. Example RPC server and client with Netty backend https://github.com/wvlet/airframe/tree/master/examples/rpc-examples/hello-rpc
