### ISSUE TITLE
AirSpec: Scala 3 support

### ISSUE THREAD

**Issue by xerial** [wvlet/airframe#1659]
- [x] Add a compat layer #1658 
- [x] Deprecate function test syntax. We should only use test("...") { (d1: D1, d2:D2, ...) => ... } syntax for consistency and reducing the complexity. This requires no reflection. #1664 
- [x] Show deprecation warning to function spec usage #1662 
- [x] Rewrite all test specs in airframe code using test(...) syntax. This can be done at ease with IntelliJ #1660
- [x] Scala 3 compatible impl #1671

**Comment by xerial** [comment]
Released as 21.5.3
