### ISSUE TITLE
Millestone: AirSpec 19

### ISSUE THREAD

**Issue by xerial** [wvlet/airframe#606]
Documentation:
- [x] Quick Start https://wvlet.org/airframe/docs/airspec.html#quick-start
- [x] How to use logging  (e.g., info, debug, etc.) and src/test/resources/log-test.properties 

Error reporting:
- [ ] Power assertion for test failures (e.g., show the condition expression and data differences)
- [x] Show the summary of succeeded/failed tests (e.g., running times per project names, failed test names) at the end. (We just need to upload target/test-reports somewhere)
- [x] Output test results to a file (sbt already reports target/test-reports)

Recording:
- [ ] Use function return values to record test results. There might be more meaningful usage of function return values (e.g., storing test data to DB, sending metrics to fluentd, etc.)

Runner:
- [x] Parallel test execution (spec level parallelism is already available)
- [ ] asynchronous tests, returning Future type 

DI
- [ ] Support `context.buildAndRun[A](additional design)` to support fine-grained design customization.

IntelliJ 
- [ ] Integration with IntelliJ (We need to file a ticket for InelliJ IDEA team) #646 
  - Starting from creating an independent plugin. 

Standalone mode
- [ ] Create a standalone launcher for running tests. #685 

Testing API
- [x] Publish a light-version of airspec without airframe classes to use it with Airframe dependencies
- [ ] Active monitoring
- [ ] smoke testing

**Comment by xerial** [comment]
We are now at the end of 2019. Moved to #839
